name: Check permissions
on:
  push:
    paths:
    - .github/workflows/check-permissions.yml
    
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -iL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rajbos/demo-actions
  
