name: Create new issue

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: rajbos-actions/workflow-application-token-action@main
      id: get_workflow_token
      with:
        application_id: ${{ secrets.GH_APPLICATION_ID }}
        application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}

    - uses: actions/github-script@v6
      name: Create new issue
      id: get-action
      with:
        result-encoding: string
        github-token: ${{ steps.get_workflow_token.outputs.token }}
        script: |                  
          const owner = context.repo.owner
          const repo = context.repo.repo          

          let title =`:robot: New issue for testing the new issue labeler :zap:`
          console.log(`Creating new issue in repo [${owner}/${repo}] with title [${title}]`)

          // create new issue
          await github.rest.issues.create({
            owner,
            repo,
            title,
            body: title
          });
