name: Create new issue

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      name: Create new issue
      id: get-action
      with:
        result-encoding: string
        github-token: ${{ secrets.GH_TOKEN }}  
        script: |                  
          const owner = context.repo.owner
          const repo = context.repo.repo          

          let title =`:robot: New issue for testing the new issue labeler :zap:`
          console.log(`Creating new issue in repo [${owner}/${repo}] with title [${title}]`)

          // create new issue
          await github.rest.issues.create({
            owner,
            repo,
            title,
            body: title
          });
