name: Do epic shit
on: 
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/do-epic-shit.yml
    
jobs:
  do-epic-shit:
    runs-on: ubuntu-latest
    steps:
    - uses: XpiritBV/doepicshit@02bb543fb5b10c6468397fa9585b2fc30dbfa300 # v1.0.1
      with:
        who-to-greet: "future Xpiriter"
