on:
  push:
    paths:
      - .github/workflows/do-not-trigger-to-often.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world"
          echo "Running from ${{ github.workflow }}"
          
      - uses: actions/github-script@v5.0.0
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            const workflow_id = "${{ github.workflow }}"
            
            console.log(`Running on repo [${owner}/${repo}] with workflow_id: [${workflow_id}]`)
            
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id
            });
            
            console.log(`Found [${runs.Length}] workflow runs`)
