on:
  push:
    paths:
      - .github/workflows/do-not-trigger-to-often.yml
      - /src/often.js

  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world"
          echo "Running from ${{ github.workflow }}"
          
      - uses: actions/github-script@v5.0.0
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            const workflow_id = "${{ github.workflow }}"


            const script = require('.src/often.js')
            console.log(script({github, owner, repo, workflow_id}))

            
