on:
  push:
    paths:
      - .github/workflows/do-not-trigger-to-often.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world"
          echo "Running from ${{ github.workflow }}"
          
      - uses: actions/github-script@v5.0.0
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            const workflow_id = "${{ github.workflow }}"
            const workflowParts = workflow_id.split('/')
            console.log(`${JSON.stringify(workflowParts)}`)
            const workflow = workflowParts[workflowParts.length-1]
            
            console.log(`Running on repo [${owner}/${repo}] with workflow_id: [${workflow}]`)
            
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id
            });
                        
            console.log(``)
            console.log(`${JSON.stringify(runs)}`
            console.log(``)
            console.log(`Found [${runs.length}] workflow runs`)
