name: Process Ids
on: 
  push:
    paths:
    - .github/workflows/process-ids.yml
    
  workflow_dispatch:
  
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
  
  windows:
    runs-on: windows-latest
    steps:
    - run: $PID
    - run: $PID
    - run: $PID
    - run: $PID
    - run: $PID
    - run: $PID

  macos:
    runs-on: macos-latest
    steps:
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
