on:
  push:
    paths:
      - .github/workflows/secrets.yml
      
jobs:
  secret-setup-1:
    runs-on: ubuntu-latest
    steps:
      - name: Token as shell variable
        run: echo "Token value [$GITHUB_TOKEN]"
        
      - name: Token injected
        env:
          token: ${{ github.token }}
        run: echo "Token value [$token]"

      - name: Token as shell variable again, should be empty?
        run: echo "Token value [$GITHUB_TOKEN]"
