name:
  workflow_debug
on:
  push:
    paths:
    - .github/workflows/workflow_debug.yml
    
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "ACTIONS_STEP_DEBUG: [${{ env.ACTIONS_STEP_DEBUG }}]"
        echo "ACTIONS_RUNNER_DEBUG: [${{ env.ACTIONS_RUNNER_DEBUG }}]"
        echo "STEP_DEBUG: [${{ env.STEP_DEBUG }}]"
        echo "RUNNER_DEBUG: [${{ env.RUNNER_DEBUG }}]"
        
        echo "RUNNER_DEBUG: [${{ runner.debug }}]"
    - env:
        context: ${{ toJSON(github) }}
      run: |
        echo "$context"
